### ISSUE TITLE
How fast is the descriptor extraction? 

### ISSUE THREAD

**Issue by billkle1n** [Relja/netvlad#10]
This is hard for me to test as I don't have Matlab and didn't find an answer in the paper. Could anyone help? I'm essentially wondering what kind of throughput this can achieve on a GPU in terms of `images/s`.

**Comment by Relja** [comment]
Hi, I'll check this for you tonight as I don't have Matlab at hand right now. 
Btw, there is an independent tensorflow implementation of NetVLAD (though they didn't use it for place recognition but for winning the Youtube-8M challenge):
https://github.com/antoine77340/LOUPE
There's also an independent caffe implementation used for place recognition:
https://github.com/hyojinie/crn

**Comment by Relja** [comment]
I checked some old logs, as right now I don't have access to a MATLAB+GPU, and as far as I can see, for a batch of 4 images that are 640x480 each (so much larger than the standard 224x224), including all overhead of loading the image and saving descriptors on disk (nothing smart done here, no pre-fetching or reading images in parallel as is generally standard in deep learning):
VGG-16 with Max on conv5_3: 1.2s
VGG-16 with NetVLAD on conv5_3: 1.75s
AlexNet with Max on conv5: 0.15s
AlexNet with NetVLAD on conv5: 0.45s
I'm not sure, but I think this was done on a K20. I did not use cuDNN, which should bring all these numbers down.
