### ISSUE TITLE
My matlab crashed when I run this code,can someone help me?

### ISSUE THREAD

**Issue by Scsy** [Relja/netvlad#12]
------------------------------------------------------------------------
       Segmentation violation detected at Tue Mar 13 09:44:53 2018
------------------------------------------------------------------------

Configuration:
  Crash Decoding      : Disabled - No sandbox or build area path
  Crash Mode          : continue (default)
  Current Graphics Driver: Unknown software 
  Current Visual      : 0x21 (class 4, depth 24)
  Default Encoding    : UTF-8
  Deployed            : false
  GNU C Library       : 2.19 stable
  Host Name           : sawei
  MATLAB Architecture : glnxa64
  MATLAB Entitlement ID: Unknown
  MATLAB Root         : /usr/local/MATLAB/R2016b
  MATLAB Version      : 9.1.0.441655 (R2016b)
  OpenGL              : software
  Operating System    : Linux 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64
  Processor ID        : x86 Family 6 Model 94 Stepping 3, GenuineIntel
  Virtual Machine     : Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : The X.Org Foundation (11803000), display :0.0

Fault Count: 1

Abnormal termination:
Segmentation violation

Register State (from fault):
  RAX = 0000000000000000  RBX = 0000000100000000
  RCX = 00007f87aa46d320  RDX = 0000000000000000
  RSP = 00007f878aa58830  RBP = 00007f878aa588e0
  RSI = 00007f878aa58420  RDI = 0000000000000000

   R8 = 0000000000000000   R9 = 00007f86e3a85450
  R10 = 00007f86b983a140  R11 = 00000000ab8d61a2
  R12 = 00007f86e3382d18  R13 = 0000000000000001
  R14 = 00007f86e36dc8a0  R15 = 0000000000000001

  RIP = 00007f86d0c82cdc  EFL = 0000000000010206

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007f86d0c82cdc   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwgpu.so+08363228
[  1] 0x00007f86d0c68b0a   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwgpu.so+08256266
[  2] 0x00007f86d0c66873   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwgpu.so+08247411
[  3] 0x00007f86d0c669f2   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwgpu.so+08247794
[  4] 0x00007f86d0c55c94   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwgpu.so+08178836
[  5] 0x00007f86d3fc979f /home/sawei/matconvnet/matlab/mex/vl_nnconv.mexa64+00034719
[  6] 0x00007f86d3fc9f99 /home/sawei/matconvnet/matlab/mex/vl_nnconv.mexa64+00036761
[  7] 0x00007f86d3fc64d8 /home/sawei/matconvnet/matlab/mex/vl_nnconv.mexa64+00021720 mexFunction+00001412
[  8] 0x00007f879ba66caa     /usr/local/MATLAB/R2016b/bin/glnxa64/libmex.so+00175274 mexRunMexFile+00000106
[  9] 0x00007f879ba5f1a3     /usr/local/MATLAB/R2016b/bin/glnxa64/libmex.so+00143779
[ 10] 0x00007f879ba60345     /usr/local/MATLAB/R2016b/bin/glnxa64/libmex.so+00148293
[ 11] 0x00007f879ad5f8a3 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_dispatcher.so+00768163 _ZN8Mfh_file16dispatch_fh_implEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000947
[ 12] 0x00007f879ad6016e /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_dispatcher.so+00770414 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000030
[ 13] 0x00007f8797b9a847 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+11675719
[ 14] 0x00007f8797b9aaab /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+11676331
[ 15] 0x00007f8797c00411 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+12092433
[ 16] 0x00007f8797526930 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04909360
[ 17] 0x00007f8797528c3c /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04918332
[ 18] 0x00007f8797525410 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903952
[ 19] 0x00007f8797520855 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04884565
[ 20] 0x00007f8797520b69 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04885353
[ 21] 0x00007f879752520d /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903437
[ 22] 0x00007f87975252e2 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+04903650
[ 23] 0x00007f879761c688 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+05916296
[ 24] 0x00007f879761eb2f /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+05925679
[ 25] 0x00007f8797a9d10e /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10637582
[ 26] 0x00007f8797a64eab /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10407595
[ 27] 0x00007f8797a64fb3 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10407859
[ 28] 0x00007f8797a670d9 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10416345
[ 29] 0x00007f8797adfbbe /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10910654
[ 30] 0x00007f8797adff4a /usr/local/MATLAB/R2016b/bin/glnxa64/libmwm_lxe.so+10911562
[ 31] 0x00007f879a0043db /usr/local/MATLAB/R2016b/bin/glnxa64/libmwbridge.so+00189403
[ 32] 0x00007f879a00507d /usr/local/MATLAB/R2016b/bin/glnxa64/libmwbridge.so+00192637 _Z8mnParserv+00000829
[ 33] 0x00007f879b021243   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00537155
[ 34] 0x00007f879b0231ce   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00545230
[ 35] 0x00007f879b023849   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00546889 _ZN5boost6detail17task_shared_stateINS_3_bi6bind_tIvPFvRKNS_8functionIFvvEEEENS2_5list1INS2_5valueIS6_EEEEEEvE6do_runEv+00000025
[ 36] 0x00007f879b022236   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00541238
[ 37] 0x00007f879b7e9b49   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00863049
[ 38] 0x00007f879b7d651c   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00783644 _ZN5boost6detail8function21function_obj_invoker0ISt8functionIFNS_3anyEvEES4_E6invokeERNS1_15function_bufferE+00000028
[ 39] 0x00007f879b7d61fc   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00782844 _ZN3iqm18PackagedTaskPlugin7executeEP15inWorkSpace_tagRN5boost10shared_ptrIN14cmddistributor17IIPCompletedEventEEE+00000428
[ 40] 0x00007f879b7b5a0a   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00649738
[ 41] 0x00007f879b7a1690   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00566928
[ 42] 0x00007f879b7a4048   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwiqm.so+00577608
[ 43] 0x00007f87ab95240a /usr/local/MATLAB/R2016b/bin/glnxa64/libmwservices.so+02634762
[ 44] 0x00007f87ab9539af /usr/local/MATLAB/R2016b/bin/glnxa64/libmwservices.so+02640303
[ 45] 0x00007f87ab9540e6 /usr/local/MATLAB/R2016b/bin/glnxa64/libmwservices.so+02642150 _Z25svWS_ProcessPendingEventsiib+00000102
[ 46] 0x00007f879b0218c6   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00538822
[ 47] 0x00007f879b021c42   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00539714
[ 48] 0x00007f879b00f8d6   /usr/local/MATLAB/R2016b/bin/glnxa64/libmwmcr.so+00465110
[ 49] 0x00007f87aa25c184              /lib/x86_64-linux-gnu/libpthread.so.0+00033156
[ 50] 0x00007f87a9f88ffd                    /lib/x86_64-linux-gnu/libc.so.6+01040381 clone+00000109
[ 51] 0x0000000000000000                                   <unknown-module>+00000000

This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.

Thanks a lot!

**Comment by Relja** [comment]
Hi,

This cannot be a problem with the NetVLAD code as there are no mex files within, it must be that there's something wrong with your MATLAB + CUDA setup, or your matconvnet installation. Please first make sure those two work, and then run the NetVLAD code.

My best bet would be that there's something wrong with your MATLAB/CUDA as it's strange it says "unknown driver". Brief Google search gave this:

http://www.discoverbits.in/105/matlab-r2016a-gives-unknown-graphics-driver-hardware-ubuntu

**Comment by Scsy** [comment]
I find some problems with my matconvnet, now I slove them and run the code successfully.
Thank you for your advice!

**Comment by shi-yan** [comment]
@Scsy what was your solution? I'm seeing it too.

**Comment by shi-yan** [comment]
I realized that every time I update the graphics driver, I need to rebuild matconvnet. After rebuilding my issue was solved.
