### ISSUE TITLE
the TokyoTM database 

### ISSUE THREAD

**Issue by Scsy** [Relja/netvlad#13]
Hi @Relja ,I find that I need the TokyoTM database to train, but in your project I don't find the download link. Can you provide it to me？
Thanks a lot!

**Comment by Relja** [comment]
As written in the paper, we provide it on request - we don't want to post the link publicly. Please email me and I'll send you the link.

**Comment by Huang9495** [comment]
@Relja Can you provide a email for me?  I sent the email according to the article but no answer.

**Comment by Relja** [comment]
Sorry about that, I respond to everyone quickly so I'm not sure why I didn't get your email. Can you please email me again at relja@relja.info and I'll send you the link.

**Comment by Relja** [comment]
@Huang9495 I didn't get an email from you yet.

**Comment by mambawj** [comment]
Hi, @Relja. Could you please send me the download link? I will only use it for research. I emailed you a few days ago. Thank you so much.

**Comment by Relja** [comment]
@mambawj Hi, sorry about that, are you sxwj1204@ .. ? It was in my spam, responding now. If not, please send me your email address.

**Comment by mambawj** [comment]
You are welcome. Yes, that`s right.  I have received your mail. Thank you very much for your help in my study. I will continue to follow your research in the future. Finally, welcome to China.^_^
