### ISSUE TITLE
The dataset used in NetVLAD

### ISSUE THREAD

**Issue by Mendel1** [Relja/netvlad#16]
Is there any other way to get those datasets, such as Tokyo 24/7? I have sent an email to Akihiko Torii before, however, There is no reply......

**Comment by Relja** [comment]
Yes, please email me and I'll send you. relja@relja.info

**Comment by Mendel1** [comment]
Thank you very much.

**Comment by AdamAsh2019** [comment]
me,too...............I have sent an email to Akihiko Torii, and he did not reply. could u please sent me download links.

**Comment by mrgransky** [comment]
@AdamAsh2019 what is his email address btw? I googled him and I could not find it!

**Comment by Relja** [comment]
@mrgransky Please email me at relja@relja.info , Akihiko Torii has stopped doing research.

**Comment by Relja** [comment]
@mrgransky ah sorry I think you actually already have emailed me straight after this comment. I'll respond soon.

**Comment by MarvelousWang** [comment]
Hello, I have sent the dataset request email to relja@relja.info. Can I get the datasets?

**Comment by Relja** [comment]
Done

**Comment by srimontidutta** [comment]
@Relja Hello, I've sent you an email. Can you please send me the datasets?

**Comment by Relja** [comment]
Done. For future requests - there's no need to write on github and notify unrelated people, emailing me is sufficient.

**Comment by XinLan12138** [comment]
> Done. For future requests - there's no need to write on github and notify unrelated people, emailing me is sufficient.

Hi. I have emailed u and wish to get a copy of Pittsburgh (Pitts250k) dataset. thanks!

**Comment by Relja** [comment]
responded to your previous email 2 days ago, maybe check spam

**Comment by yutongwangBIT** [comment]
Dear Relja,  I have emailed u and wish to get a copy of the datasets. thanks!

**Comment by Relja** [comment]
Done. For future requests - there's no need to write on github and notify unrelated people, emailing me is sufficient.

**Comment by snmsung716** [comment]
Hi. I emailed u and hope to get a copy of tokyo (Tokyo 24/7) dataset. thanks!
