### ISSUE TITLE
A problem with dataset "Tokyo247"

### ISSUE THREAD

**Issue by Sunny-Yu** [Relja/netvlad#21]
hello!
I followed the instructions of "readme" and used the database "Tokyo247". However, a problem occurred to me. What is relationship between query images, database and test images? After finishing reading your paper, I assumed the test image play the role of query image.
By the way, if I want to train my own network using Pytorch , the length of triplet is fixed? and how can I choose the potential positive images and how can I choose the firm negative ones. The details are confusing to me.

**Comment by Relja** [comment]
Please reread the paper and other relevant papers - we follow a standard procedure used to evaluate location recognition. Tokyo 24/7 is an existing dataset, we didn't define the evaluation procedure for it, read that paper. Specifically: dataset in general have training, validation and test splits. In principle, for EACH split, there are query and database images. Specifically, Tokyo 24/7 is a dataset that is test-only, it doesn't have training or validation, so to train we introduce the Tokyo Time Machine dataset, which has training and validation splits. To evaluate, you take the test dataset (Tokyo 24/7) and search with each of the query images in turn to evaluate the performance.

Definitions of the potential positives and triplet can be found in the paper text:

To create the training tuple for a query, we use all of
its potential positives (images within 10 meters), and we
perform randomized hard negative mining for the negatives
(images further away than 25 meters). The mining is done
by keeping the 10 hardest negatives from a pool of 1000 randomly
sampled negatives and 10 hardest negatives from the
previous epoch. We find that remembering previous hard
negatives adds stability to the training process.
