### ISSUE TITLE
how to set（imPath,imageFns）

### ISSUE THREAD

**Issue by la735681253** [Relja/netvlad#25]
whether the imPath is the folder which include  images？ but how to set the imageFns？

**Comment by Relja** [comment]
I presume you are asking about computing features with `serialAllFeats(net, imPath, imageFns, outputFn);`
As explained in the line below that one in the README:

"imageFns is a cell array containing image file names relative to the imPath (i.e. [imPath, imageFns{i}] is a valid JPEG image)"

I don't know what images you want to use. If it's any random image you want to extract features from, you need to make the two variables yourself. If you want to use one of the supported datasets, these are provided for you (as long as you point the code to the dataset). It's all explained in the README a few lines below the sentence I cited.

**Comment by la735681253** [comment]
i am sorry i don’t say clearly ，now i want to use my own dataset which the folder is named ‘Data/images’ ，and it has 1000 images，each filename is 0001.jpg、0002.jpg…1000.jpg.
my problem is i don‘t know how to make the imPath and imageFns.


i guess the impath = ‘‘Data/images’，is it right？how about imageFns？


can you give me a example 
thank your very much



发自我的iPhone

------------------ Original ------------------

**Comment by Relja** [comment]
Yes `imPath` should be the path to the folder, but it should be absolute, i.e. `/home/bla/bla/Data/images/` . `imageFns` should be a cell array of image names such that `[imPath, imageFns{i}]` is an image. E.g. 

    imageFns = cell(1000,1);
    for i = 1:1000
      imageFns{i} = sprintf('%04d.jpg', i);
    end
