### ISSUE TITLE
Pre-trained Caffe Models for python utilization

### ISSUE THREAD

**Issue by mrgransky** [Relja/netvlad#28]
Do you guys also have `deploy.prototxt` and `model.caffemodel` files compatible with python?

Or is there any workaround to convert those `.mat` model files into `deploy.prototxt` and `model.caffemodel` to apply for feature extraction in python?

Cheers,

**Comment by Relja** [comment]
Hi,
Our implementation is only in MATLAB / MatConvNet. However multiple other groups have imported models to other frameworks like tensorflow and pytorch. I'm not aware of caffe models as caffe is also not popular these days. Here's a random few I found on Google - I never used them myself so can't endorse them, but I expect them to be good:

https://github.com/uzh-rpg/netvlad_tf_open
https://github.com/mcimpoi/pytorch-NetVlad
http://www.robots.ox.ac.uk/~albanie/pytorch-models.html
but I'm sure you can find more.

Best,
Relja
