### ISSUE TITLE
NetVLAD for place recognition in sequential images (SLAM) 

### ISSUE THREAD

**Issue by mrgransky** [Relja/netvlad#29]
Apologies if my question sounds dumb!

I would like to know if it makes sense to use netvlad for place recognition of problems dealing with sequences of images (SLAM) over seasonal changes (no specific viewpoint changes)?

What I have in mind is [Nordland](https://webdiis.unizar.es/~jmfacil/pr-nordland/) dataset in which images rather suffer from illumination changes over seasons. 

Cheers,

**Comment by Relja** [comment]
Sure, if you google Nordland and NetVLAD you'll get several papers that use it in one way or another. NetVLAD and SLAM also give quite a few results. I am not very familiar with any of these, but it certainly can be done.
