### ISSUE TITLE
Cartesian coordinates

### ISSUE THREAD

**Issue by ghost** [Relja/netvlad#34]
Hello, thanks for sharing code.

I have dataset from simulator. Each of image has txt file with cartesian coordinates. I don't have GPS data, therefore I don't have UTM data.
What should I change/add in your code so that I can make dbStruct and class of dataset by use cartesian coordinates?

**Comment by Relja** [comment]
Hi,
UTM coordinates is basically local flattening of the polar GPS coordinates onto Cartesian coordinates. Distance between two points in UTM space is basically the distance in meters between the two points (approximated by flattening the Earth, so ok on city-scale). So you should just use UTM = your Cartesian data.
