### ISSUE TITLE
How to choose good number of cluster and dimension?

### ISSUE THREAD

**Issue by RaymondLmx** [Relja/netvlad#35]
The feature is small in my experiments which is [1, 1024]. This shape is far small than that in your experiments. So how can I choose my cluster number and dimension number?

**Comment by Relja** [comment]
Like many other things such, there is no general answer about the "best" number of clusters. Typically more clusters is better if you have many features and enough training data to learn this, but it also produces larger NetVLAD vectors. As with other related works like VLAD, Fisher Vectors, etc you just have to experimentally see what works.
