### ISSUE TITLE
the TokyoTM database

### ISSUE THREAD

**Issue by liu-710** [Relja/netvlad#36]
Hi @Relja ,I am a student and I am learning about your netvlad.

After browsing the relevant home page, I have completed the basic configuration, but the next work lacks the database file. I learned from others that I need to send an application to you. Can you provide it to me? My email address is 18260627915@163.com .

Thank you very much.

At the same time, there are some configuration problems. I run the code on win10 system, but I see Yael_ matlab_ linux64_ V438 doesn't fit with win. If I don't download matlab from Ubuntu to reconfigure, is the path set to Yael_ The path to the dummy file?

**Comment by liu-710** [comment]
And I want to know the difference between the functions of Tokyo time machine and Tokyo 24 / 7. If you can, please share the Tokyo 24 / 7 database. Thank you.

**Comment by Relja** [comment]
Hi @liu-710 , I sent you an email now.

I don't know about Yael and windows, their website says they don't support windows but there are some external forks that do. If you google "yael library windows" there are lots of results.

You can use the dummy path if you want - it should work but it will be slower. Or you can replace this with any other fast nearest neighbour search library, it just needs to be able to do a KNN search in a database of vectors. I also use it for k-means but matlab's k-means is probably good enough, and k-means is only done once, not during training,

I don't understand your question on Tokyo Time Machine vs Tokyo 24/7 "functions". These are two different datasets, the former is introduced in our NetVLAD paper and the latter in an earlier work "24/7 place recognition by view synthesis".
