### ISSUE TITLE
pitts30k datasets

### ISSUE THREAD

**Issue by yu1206** [Relja/netvlad#37]
pitts30k datasets
Hello, please send me the database, thank you.

**Comment by Relja** [comment]
Please send me an email (relja@relja.info) and I'll respond to it.

**Comment by yu1206** [comment]
792496814@qq.com

**Comment by 1392020988** [comment]
pitts30k datasets
Hello, please send me the database, thank you.
1392020988@qq.com

**Comment by fangfang11-plog** [comment]
pitts30k datasets
Hello, please send me the database, thank you.
[1229159746@qq.com](mailto:1229159746@qq.com)

**Comment by Relja** [comment]
Please send me an email ([relja@relja.info](mailto:relja@relja.info)) and I'll respond to it. Future interested people: please don't write here but just email me.

**Comment by liangyongshi** [comment]
shiyongliang@air.tsinghua.edu.cn

**Comment by liangyongshi** [comment]
pitts30k datasets
Hello, please send me the database, thank you.
shiyongliang@air.tsinghua.edu.cn

**Comment by Relja** [comment]
As explained above, please email me and don't write here in order not to spam other people on this issue.

**Comment by liangyongshi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，已经收到您的邮件，无法亲自回复，还请见谅。

**Comment by 1392020988** [comment]
Dear researcher,


Thank you for your interest in our work. The links towards datasets are listed below.


If you are using the NetVLAD code that we provide, then you just need to:
- Download the dataset specifications from our project page (&nbsp;http://www.di.ens.fr/willow/research/netvlad/&nbsp;)
- Update the localPaths.m to link to the places where you extracted the datasets and the dataset specifications


Best Regards,
Relja




The datasets can be downloaded here:






—&nbsp; 24/7 Tokyo ---
&nbsp;
1. Please find the 24/7 Tokyo GSV perspective images at:
https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Tokyo247/database_gsv_vga/


2. Queries
https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Tokyo247/queries/

Version 2 is what was used in that paper, as well as my NetVLAD paper, so if you want to compare results, you should use this one. Version 3 contains some additional images and/or ground truth changes - these are from the PAMI version of our Tokyo 24/7 paper.
Please note that the query images should be downscaled to 640x480 for fair comparison with our work.






—&nbsp; Tokyo Time Machine —


https://data.ciirc.cvut.cz/public/projects/2015netVLAD/TokyoTimeMachine/


md5sum:


d2baaf42831eec223634f0bc7b5a1f50&nbsp; tokyoTimeMachine_v100.tar.00
ea67e41022639c0adf7ddc10bd19d686&nbsp; tokyoTimeMachine_v100.tar.01
36135c11940d92c1cd1f229352e89a91&nbsp; tokyoTimeMachine_v100.tar.02
7746d848a6959851314af761ddba307d&nbsp; tokyoTimeMachine_v100.tar.03
19c3a3b52781d499e19a17b4883a4152&nbsp; tokyoTimeMachine_v100.tar.04
e61c01ff4961249cf27f08d6e803126a&nbsp; tokyoTimeMachine_v100.tar.05
dab5dba2a9b6683822770e0b318c5f7a&nbsp; tokyoTimeMachine_v100.tar.06
208857c3bdfc2c172125e2dfa827c32c&nbsp; tokyoTimeMachine_v100.tar.07
2a0217c77d392ee98919458d1e2e668b&nbsp; tokyoTimeMachine_v100.tar.08
99438c14250224a227e0306287a23002&nbsp; tokyoTimeMachine_v100.tar.09
c4697d5f43693548a33f90a3f7c85d45&nbsp; tokyoTimeMachine_v100.tar.10
1c3db6757b68747f505d5ac1ea5ff5ce&nbsp; tokyoTimeMachine_v100.tar.11
6228047e29b9506d9b8c25daf1024967&nbsp; tokyoTimeMachine_v100.tar.12
eaddeb529fc3853ccaadb379f1f82f19&nbsp; tokyoTimeMachine_v100.tar.13


To uncompress, do:


cat tokyoTimeMachine*.tar* | tar -xf -






—&nbsp; Pittsburgh 250k —


1. Please find the Pittsburgh 250k at:
https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Pittsburgh250k/



- The dataset images is in ***.tar
md5sum's:
3edec2fac461f4a740a21d509ad6e30e&nbsp; 000.tar
c97e5fffd53a2387f1f57b3ec3cae5cb&nbsp; 001.tar
afab887a76f8c4b5c017bd51ea105f5c&nbsp; 002.tar
f217320114299249ea6ebbd71eeb76de&nbsp; 003.tar
00ae08d9020b953c4e1125da5054577c&nbsp; 004.tar
be3fd968f96ebf2548adec23e94a8eb8&nbsp; 005.tar
89818a0841ec98a7b017ded678372652&nbsp; 006.tar
16cbd960c37715e73166d1c1361e337b&nbsp; 007.tar
589ce95e50038dccd012e4fc429bd3e3&nbsp; 008.tar
3f9de2504fddf140f17c6c8b4315a09e&nbsp; 009.tar
5175571cf6f0061aced10fb65e0c9691&nbsp; 010.tar


2. The query images are in queries_real.tar. It containes the 24000 query images that are actually used.
md5sum:
5611c4d601c92f6c7dd702fc2716914a&nbsp; queries_real.tar







—&nbsp; Pittsburgh 30k —


This is a subset of&nbsp;Pittsburgh 250k. Unfortunately there is no separate prepackaged archive for this - download Pittsburgh 250k and the dataset specifications (mentioned at the beginning of this email) contain the information on which images form Pittsburgh 30k.







On Sat, 3 Sept 2022 at 14:16, 时间总在说谎 ***@***.***&gt; wrote:

Hi friend, I'm sorry to bother you，can you give me the data set of Tokyo 24/7?&nbsp; I really can't do anything, so I ask for your help, thank you very much!Looking forward to your reply！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月3日(星期六) 下午4:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Relja/netvlad] pitts30k datasets (#37)














 
pitts30k datasets
 Hello, please send me the database, thank you.
 ***@***.***

**Comment by 1392020988** [comment]
Dear researcher,


Thank you for your interest in our work. The links towards datasets are listed below.


If you are using the NetVLAD code that we provide, then you just need to:
- Download the dataset specifications from our project page (&nbsp;http://www.di.ens.fr/willow/research/netvlad/&nbsp;)
- Update the localPaths.m to link to the places where you extracted the datasets and the dataset specifications


Best Regards,
Relja




The datasets can be downloaded here:






—&nbsp; 24/7 Tokyo ---
&nbsp;
1. Please find the 24/7 Tokyo GSV perspective images at:
https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Tokyo247/database_gsv_vga/


2. Queries
https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Tokyo247/queries/

Version 2 is what was used in that paper, as well as my NetVLAD paper, so if you want to compare results, you should use this one. Version 3 contains some additional images and/or ground truth changes - these are from the PAMI version of our Tokyo 24/7 paper.
Please note that the query images should be downscaled to 640x480 for fair comparison with our work.






—&nbsp; Tokyo Time Machine —


https://data.ciirc.cvut.cz/public/projects/2015netVLAD/TokyoTimeMachine/


md5sum:


d2baaf42831eec223634f0bc7b5a1f50&nbsp; tokyoTimeMachine_v100.tar.00
ea67e41022639c0adf7ddc10bd19d686&nbsp; tokyoTimeMachine_v100.tar.01
36135c11940d92c1cd1f229352e89a91&nbsp; tokyoTimeMachine_v100.tar.02
7746d848a6959851314af761ddba307d&nbsp; tokyoTimeMachine_v100.tar.03
19c3a3b52781d499e19a17b4883a4152&nbsp; tokyoTimeMachine_v100.tar.04
e61c01ff4961249cf27f08d6e803126a&nbsp; tokyoTimeMachine_v100.tar.05
dab5dba2a9b6683822770e0b318c5f7a&nbsp; tokyoTimeMachine_v100.tar.06
208857c3bdfc2c172125e2dfa827c32c&nbsp; tokyoTimeMachine_v100.tar.07
2a0217c77d392ee98919458d1e2e668b&nbsp; tokyoTimeMachine_v100.tar.08
99438c14250224a227e0306287a23002&nbsp; tokyoTimeMachine_v100.tar.09
c4697d5f43693548a33f90a3f7c85d45&nbsp; tokyoTimeMachine_v100.tar.10
1c3db6757b68747f505d5ac1ea5ff5ce&nbsp; tokyoTimeMachine_v100.tar.11
6228047e29b9506d9b8c25daf1024967&nbsp; tokyoTimeMachine_v100.tar.12
eaddeb529fc3853ccaadb379f1f82f19&nbsp; tokyoTimeMachine_v100.tar.13


To uncompress, do:


cat tokyoTimeMachine*.tar* | tar -xf -






—&nbsp; Pittsburgh 250k —


1. Please find the Pittsburgh 250k at:
https://data.ciirc.cvut.cz/public/projects/2015netVLAD/Pittsburgh250k/



- The dataset images is in ***.tar
md5sum's:
3edec2fac461f4a740a21d509ad6e30e&nbsp; 000.tar
c97e5fffd53a2387f1f57b3ec3cae5cb&nbsp; 001.tar
afab887a76f8c4b5c017bd51ea105f5c&nbsp; 002.tar
f217320114299249ea6ebbd71eeb76de&nbsp; 003.tar
00ae08d9020b953c4e1125da5054577c&nbsp; 004.tar
be3fd968f96ebf2548adec23e94a8eb8&nbsp; 005.tar
89818a0841ec98a7b017ded678372652&nbsp; 006.tar
16cbd960c37715e73166d1c1361e337b&nbsp; 007.tar
589ce95e50038dccd012e4fc429bd3e3&nbsp; 008.tar
3f9de2504fddf140f17c6c8b4315a09e&nbsp; 009.tar
5175571cf6f0061aced10fb65e0c9691&nbsp; 010.tar


2. The query images are in queries_real.tar. It containes the 24000 query images that are actually used.
md5sum:
5611c4d601c92f6c7dd702fc2716914a&nbsp; queries_real.tar







—&nbsp; Pittsburgh 30k —


This is a subset of&nbsp;Pittsburgh 250k. Unfortunately there is no separate prepackaged archive for this - download Pittsburgh 250k and the dataset specifications (mentioned at the beginning of this email) contain the information on which images form Pittsburgh 30k.







On Sat, 3 Sept 2022 at 14:16, 时间总在说谎 ***@***.***&gt; wrote:

Hi friend, I'm sorry to bother you，can you give me the data set of Tokyo 24/7?&nbsp; I really can't do anything, so I ask for your help, thank you very much!Looking forward to your reply！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Relja/netvlad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月11日(星期四) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Relja/netvlad] pitts30k datasets (#37)





 
pitts30k datasets
 Hello, please send me the database, thank you.
 ***@***.***

**Comment by Coldebaby** [comment]
pitts30k datasets
Hello, please send me the database, thank you.
wuyu1934563573@163.com

**Comment by liangyongshi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，已经收到您的邮件，无法亲自回复，还请见谅。

**Comment by jokerGrimm** [comment]
please send me the database, thank you.
jiangbin9711@163.com

**Comment by Lanbo-Wu-370373** [comment]
Hello, please send me the dataset
wulanbo92@gmail.com

**Comment by liangyongshi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，已经收到您的邮件，无法亲自回复，还请见谅。

**Comment by FANRUIHAO** [comment]
Hello, could you please send me the **pitts30k database**, thank you.
This is my email: 
25014083009@stu.hqu.edu.cn
