### ISSUE TITLE
Dimensions of matrices being concatenated are not consistent. In serialALLFeats() function

### ISSUE THREAD

**Issue by BeSlower** [Relja/netvlad#4]
error on this sentence:  
ims= cat(4, ims_{:});

for images have different dimensions, there will be an error.
In my experiments, the size of ims_{1} is 1024x683 while the size of ims_{2} is 683x1024
Could you give me some suggestions? Thanks a lot.

**Comment by Relja** [comment]
The documentation of that function states

```
%  `batchSize': The number of images to process in a batch. Note that if your
%       input images are not all of same size (they are in place recognition
%       datasets), you should set `batchSize` to 1.
```

There is no other simple way of fixing this - matconvnet (and likely all convnet libraries) require that images which make the batch are of the same size.
