### ISSUE TITLE
about Pittsburgh 250k dataset

### ISSUE THREAD

**Issue by XiaozhuLove** [Relja/netvlad#41]
Hope you are fine. Thanks for your amazing work. Sorry to bother you here ,  I have sent you an email for the dataset ,but  I haven't received your reply, have you received any email from me? my email name is zhuxiaozx.  Sorry to bother you here again! Looking forward to your reply,thanks a lot!

**Comment by Relja** [comment]
Sorry, your email was in spam, I responded now.
