### ISSUE TITLE
Questions about Pitts250k dataset panoramic image splitting

### ISSUE THREAD

**Issue by zafirshi** [Relja/netvlad#46]
Hello, thank you for your work on the VPR task.:clap: I have some questions about pitts250k dataset

1. One panoramic image is cut into 24 perspective images according to two yaw Directions [4, 26.5] and 12 pitch [0, 30,..., 360] directions. How is it done? Is there a code?

2. I found that some objects have strange problems after cutting, such as: the lamp on the roadside lamp pole is separated from the pole, and there is a lateral dislocation in the middle. Is this caused by cutting the panoramic image?

3. My current research needs the original panorama (before cutting), but collecting data by yourself is a labor-intensive work. Can you share it with me if it is convenient? Or can you tell me the **_focal length_** of the perspective image after cutting, so that the cut images can be restored on the cylinder by projection?

Do you have any better suggestions? Looking forward to your early reply!:smiley:

**Comment by Relja** [comment]
Hi,

I'm affraid I won't be very useful as I am not very familiar with the data collection process - I was most responsible for the method part while collect was done by Akihiko Torii (not doing research any more) and Petr Gronat (not sure about his availability, maybe you can try contacting him?)

1. Not sure and I'm affraid code might be lost by now, e.g. I think this was done by Akihiko and he is not contactable.
2. As far as I understand this is not the problem of cutting but the original panoramas have this issue. I don't know the details but my understanding is that Google captures multiple images from different cameras and stitches them together, so artefacts can happen. Cutting shouldn't really introduce artefacts such as lateral dislocation as it should just be a matter of applying a projection and crop.
3. I'm affraid the original panoramas are likely lost as 7 years is a long time for an academic lab, people have moved, computers changed etc. You can try your luck with Petr Gronat but I doubt he has them. At the time he released this code https://github.com/gronat/streetget/tree/master/streetget but I don't know what's the state of that, presumably Google's APIs changed etc.

Good luck!
