### ISSUE TITLE
How to run the Trained Network Matlab

### ISSUE THREAD

**Issue by jdanielhoyos** [Relja/netvlad#47]
Hello, I just imported the .mat trained network, but I don't know how to pass it an image to obtain the  depth estimation, would you please give me an explante? 
Thanks!

**Comment by Relja** [comment]
As explained in the readme, you can look at demo.m to see how to run the network. Before that you should go through other steps of the readme, e.g. install dependencies.
However, this network does not do depth estimation, my NetVLAD work doesn't do that.
