### ISSUE TITLE
using in real time application

### ISSUE THREAD

**Issue by rafal7466** [Relja/netvlad#48]
Hi
Can we use the trained model in the real-time application? and which GPU can be used in real-time?

**Comment by Relja** [comment]
It all depends on your backbone network and the size of the dataset. You probably want a more modern implementation (e.g. in tensorflow, pytorch or jax) to compute features fast, but also if your dataset is large you want a good approximate nearest neighbour search method. The NetVLAD layer itself is pretty light, so it's easy for you to estimate the speed - estimate how fast is a forward pass for the network you need, and how fast is ANN search with the feature dimesionality and database size in your setup.
