### ISSUE TITLE
About demo test

### ISSUE THREAD

**Issue by ionLi** [Relja/netvlad#49]
- When   I run this demo, I meet a error.

serialAllFeats: Start
serialAllFeats 09-Nov-2022 11:07:26 1 / 7599
73          if iBatch==1
serialAllFeats 09-Nov-2022 11:31:06 2 / 7599; time 00:23:40; left 2997:29:09; avg 1420.2355 s
serialAllFeats 09-Nov-2022 11:31:19 3 / 7599; time 00:23:52; left 1511:52:57; avg 716.4378 s
serialAllFeats 09-Nov-2022 11:31:51 4 / 7599; time 00:24:24; left 1030:00:57; avg 488.1592 s
serialAllFeats 09-Nov-2022 11:32:05 8 / 7599; time 00:24:38; left 445:34:30; avg 211.2844 s
serialAllFeats 09-Nov-2022 11:32:08 16 / 7599; time 00:24:42; left 208:10:14; avg 98.8152 s
serialAllFeats 09-Nov-2022 11:32:15 32 / 7599; time 00:24:48; left 100:57:08; avg 48.0217 s
serialAllFeats 09-Nov-2022 11:32:28 64 / 7599; time 00:25:01; left 49:53:44; avg 23.8356 s
serialAllFeats 09-Nov-2022 11:32:54 128 / 7599; time 00:25:27; left 24:57:55; avg 12.0283 s
serialAllFeats 09-Nov-2022 11:33:46 256 / 7599; time 00:26:20; left 12:38:29; avg 6.1968 s
serialAllFeats 09-Nov-2022 11:35:31 512 / 7599; time 00:28:05; left 06:29:33; avg 3.2976 s
serialAllFeats 09-Nov-2022 11:37:12 759 / 7599; time 00:29:46; left 04:28:39; avg 2.3564 s
serialAllFeats 09-Nov-2022 11:39:02 1024 / 7599; time 00:31:36; left 03:23:09; avg 1.8537 s
错误使用 fwrite
文件标识符无效。使用 fopen 生成有效的文件标识符。

出错 serialAllFeats (line 79)
            fwrite(fout, buffer(:, 1:numInBuffer), class(buffer));

出错 demo (line 93)
serialAllFeats(net, dbTest.dbPath, dbTest.dbImageFns, dbFeatFn, 'batchSize', 10); % adjust batchSize depending on your GPU /
network size

- I find that the reason for this error is there is no file called vd16_tokyoTM_conv5_3_vlad_preL2_intra_white_tokyo247_db.bin.

In demo.m  
dbFeatFn= sprintf('%s%s_%s_db.bin', paths.outPrefix, netID, dbTest.name);

But I don't find the introduction about   this file. So should I create this file myself.
Thanks.

**Comment by Relja** [comment]
Hi,
The code is trying to create the file and write features to it. I'm not exactly sure because of Chinese but it seems it fails at fopen in write mode, or fails to write to the opened file. Are you sure you have disk space and write permission to the folder you are trying to write to? Maybe you didn't set up the [outPath](https://github.com/Relja/netvlad/blob/master/localPaths.m.setup#L45) correctly? I don't know if matlab has some issues with non-unicode characters, though nobody complained about that so far.

**Comment by ionLi** [comment]
I think it fails because there is not a file called vd16_tokyoTM_conv5_3_vlad_preL2_intra_white_tokyo247_db.bin, this file is be created by the code "dbFeatFn= sprintf('%s%s_%s_db.bin', paths.outPrefix, netID, dbTest.name);",which in the demo.m 
I don't find the introduction about this file. So should I proactively create this file manually in the corresponding path？

**Comment by Relja** [comment]
`dbFeatFn= sprintf('%s%s_%s_db.bin', paths.outPrefix, netID, dbTest.name)` doesn't create the file, it makes the name of the file. This file is then being created by the `serialAllFeats` function. This [line](https://github.com/Relja/netvlad/blob/master/serialAllFeats.m#L76) in the function creates the file and opens it for writing, and [this line](https://github.com/Relja/netvlad/blob/master/serialAllFeats.m#L81) tries to write to it.
I just noticed your log says the line `fwrite(fout, buffer(:, 1:numInBuffer), class(buffer));` is number 79 while it is actually line number 81 in the original file - did you delete some code?

**Comment by ionLi** [comment]
Ok, thinks , I think it's probably I don't give the permission to create the new folder. Thank you very much.
