### ISSUE TITLE
Does NetVLAD support parallel features extraction using multiple GPUs?

### ISSUE THREAD

**Issue by ieted** [Relja/netvlad#5]
How can I use multiple GPUs (several K20m) to extract features on large dataset? Thanks in advance.

**Comment by Relja** [comment]
Hi,
I've never used the code with multiple GPUs, and I guess it depends on whether you want to process each image with multiple GPUs or you just want to parallelize by splitting images across GPUs. Not sure why would one do the former, while the latter is very simple to implement with existing code (I.e. call serialAllFeats with different chunks of the input image list, then just concatenate the output feature files)

**Comment by ieted** [comment]
Thanks for replying, @Relja .
I am in the latter case you mentioned and yes I finally solved the problem by using multi-threads with different chunks of the input images list. Things works fine now.
