### ISSUE TITLE
What is the difference between these two NetVLAD programs?

### ISSUE THREAD

**Issue by wpumain** [Relja/netvlad#51]
https://github.com/Nanne/pytorch-NetVlad     and  https://github.com/Relja/netvlad/      
What is the difference between these two NetVLAD programs?

**Comment by Relja** [comment]
This is the official implementation of NetVLAD by the authors (I am the first author of the paper). It was unfortunately written in MATLAB which is not popular any more especially for deep learning, so other people have reimplemented it in pytorch and tensorflow.

**Comment by wpumain** [comment]
Think you for your help!

**Comment by wpumain** [comment]
NetVLAD is an epoch-making work。
It is strongly recommended that you produce an official pytorch version of the NetVLAD network

**Comment by Relja** [comment]
Thanks, but I don't have the time to do it now as I've progressed to other research directions. Hopefully the independent reimplementations are sufficient.
