### ISSUE TITLE
Where can I get Pitts250k data?

### ISSUE THREAD

**Issue by wpumain** [Relja/netvlad#52]
I didn't find a way to get the data from this article 【NetVLAD: CNN architecture for weakly supervised place recognition】。
Is this data obtained from here【https://github.com/Relja/netvlad/tree/master/datasets】?
But this URL does not introduce the structure of this data Pitts250k.
Where is this data structure introduced?

**Comment by Relja** [comment]
The github page contains only code, the [readme](https://github.com/Relja/netvlad) redirects to the [project page](https://www.di.ens.fr/willow/research/netvlad/). This gives the link for the "data specification" (e.g. ground truth locations of all images) while it says to contact me if you need the actual datasets (images). If you need the images, please email me at relja@relja.info
