### ISSUE TITLE
Is it possible to convert to ONNX format?

### ISSUE THREAD

**Issue by fettahyildizz** [Relja/netvlad#55]
Is it possible to convert to ONNX format? We want to work with TensorRT environment for runtime purpose.

**Comment by Relja** [comment]
Hi,
Sorry I don't know about this as I never used pytorch and haven't been working on NetVLAD-related stuff in 7 years.
Let me point you to a previous thread:
https://github.com/Relja/netvlad/issues/43
Also there are some pytorch reimplementations of NetVLAD, e.g. you could try this:
https://github.com/Nanne/pytorch-NetVlad
