### ISSUE TITLE
pitts30k

### ISSUE THREAD

**Issue by yzxyzxyzxyzxyzx** [Relja/netvlad#56]
Dear friend:
                   please,could you send me pitts30k datasets?
                   thank you

my email is:  1329685499@qq.com

**Comment by ausu0917** [comment]
Dear friend:
please,could you send me pitts30k datasets?
thank you

my email is: [724637649@qq.com](mailto:724637649@qq.com)

**Comment by Relja** [comment]
As explained in other threads, please email me relja@relja.info
