### ISSUE TITLE
Matlab Or Octave?

### ISSUE THREAD

**Issue by guiyang882** [Relja/netvlad#7]
hi Relja,
I want to run this Project, I use Centos, so I want to know your proj can run on the octave ?

thx !

**Comment by Relja** [comment]
Sorry, I have no idea if it runs on octave, I only ever tried it with matlab. It's probably good to check first if the MatConvNet dependency runs on octave, and a quick check googling seems to suggest people don't know, and it seems octave is lacking with gpu support. If you manage to get MatConvNet to run on octave, then I think it's likely it won't be too hard to port NetVLAD , but I don't really know what are the differences so I can't say.
