### ISSUE TITLE
Is this code correct?

### ISSUE THREAD

**Issue by YLRong** [Relja/netvlad#9]
In file: **netvlad/yael_dummy/yael_nn.m**
``
ds= sum( bsxfun(@minus, v, q(:,1)).^2, 1 );
``
Should it be as following?
``
ds= sum( bsxfun(@minus, v, q(:,iVec)).^2, 1 );
``

**Comment by Relja** [comment]
Hi,
Thanks for this. Yes I think you are right, I'll fix it in a few days as I'm on holiday right now so don't have easy access. Sorry for the bug - the files in this folder are truely "dummy" as I never used them and only provided them for people who don't want to install yael, and I also think the NetVLAD code only uses single queries anyway (might be wrong). But using yael makes everything much faster so I really recommend you to install it if you haven't.
